### ISSUE TITLE
'GreeterDeployment' has already been declared

### ISSUE THREAD

**Issue by willhennessy** [symfoni/hardhat-react-boilerplate#2]
Hi team, thank you for making this template! I cloned, installed, and started the hardhat node per instructions, but 'yarn start' triggers the following build error:

```
./src/hardhat/SymfoniContext.tsx
SyntaxError: /symfoni/frontend/src/hardhat/SymfoniContext.tsx: Identifier 'GreeterDeployment' has already been declared (8:7)

   6 | import Web3Modal, { IProviderOptions } from "web3modal";
   7 | import GreeterDeployment from "./deployments/localhost/Greeter.json";
>  8 | import GreeterDeployment from "./deployments/localhost/Greeter.json";
     |        ^
   9 | import { Greeter } from "./typechain/Greeter";
  10 | import { Greeter__factory } from "./typechain/factories/Greeter__factory";
```

Investigating SymfoniContext.tsx shows more instances where a Greeter line of code is repeated 2x:

```
export const GreeterContext = React.createContext<SymfoniGreeter>(emptyContract);
export const GreeterContext = React.createContext<SymfoniGreeter>(emptyContract);

 const [Greeter, setGreeter] = useState<SymfoniGreeter>(emptyContract);
 const [Greeter, setGreeter] = useState<SymfoniGreeter>(emptyContract);

 const getGreeter = (_provider: providers.Provider, _signer?: Signer) => {
 const getGreeter = (_provider: providers.Provider, _signer?: Signer) => {
```

 Since this is an autogenerated filed, I suspect something is wrong in the build path. What do you think?

**Comment by nazariyv** [comment]
+1 I have to manually delete those duplicate lines. And even then seems like there is some other issue. The set greeter transaction gets reverted.

**Comment by nazariyv** [comment]
ignore the last bit about txn revert. It was because I was not on localhost enpoint in Metamask. The front should not load if you are on other networks.

**Comment by RobertoSnap** [comment]
Hi @willhennessy 

Thank you for posting the issue. Seems that something is wrong with our new contract instance feature. Will resolve this immediately.

**Comment by RobertoSnap** [comment]
Fixed in https://github.com/symfoni/hardhat-react-boilerplate/commit/11de38bbf64d0f886e06207b64284f07d37aa3e7

Version 0.1.13 of Hardhat-react. 

There was a bug in resolving the artifact file after added the contract instance feature.

**Comment by RobertoSnap** [comment]
@nazariyv Thanks for the feedback, should not need to manually delete those files now :)

**Comment by nazariyv** [comment]
thank you @RobertoSnap
