### ISSUE TITLE
Frontend failed to compile after following all the steps in the documentation

### ISSUE THREAD

**Issue by victorcarvalhosp** [symfoni/hardhat-react-boilerplate#7]
Hi team,

Our team is trying to run this project, but we get the same error all the time after following all the steps required in the Readme:

![image](https://user-images.githubusercontent.com/4266657/137606267-e0c8d231-bda1-4ddc-88f4-ab47145b4da5.png)

```
/home/victor/dev/MyProject/frontend/src/hardhat/SymfoniContext.tsx
TypeScript error in /home/victor/dev/MyProject/frontend/src/hardhat/SymfoniContext.tsx(117,17):
Type 'JsonRpcSigner' is not assignable to type 'Signer'.
  The types returned by 'provider.getGasPrice()' are incompatible between these types.
    Type 'Promise<import("/home/victor/dev/MyProject/frontend/node_modules/@ethersproject/contracts/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber>' is not assignable to type 'Promise<import("/home/victor/dev/MyProject/frontend/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber>'.  TS2322

    115 |             case "web3modal":
    116 |                 const web3provider = _provider as ethers.providers.Web3Provider
  > 117 |                 return await web3provider.getSigner()
        |                 ^
    118 |             case "hardhat":
    119 |                 return ethers.Wallet.fromMnemonic("test test test test test test test test test test test junk").connect(_provider)
    120 |             default:
```

Is this boilerplate project actually working? I got it from the documentation: https://hardhat.org/plugins/hardhat-react.html

Starting from scratch and trying to follow the documentation without the boilerplate project was unsuccessful for everyone that tried on our end too. :\

**Comment by CarterAppleton** [comment]
@victorcarvalhosp hope this isn't too late :) 

I had the same issue, it looks like the projects (the overall project and the `frontend` project) are pulling in different versions of `ethers` (one has `@ethersproject` as a dependency probably without version requirements, and is pulling the `provider` and other things from that. It looks like `@ethersproject` was recently updated for the EIP1559 change and added the `getGasPrice` function.. so the different versions won't match).

I was able to get around this by 
1. Changing the `ethers` version in `./package.json` to `5.5.1`
2. Changing the `ethers` version in `./frontend/package.json` to `5.5.1` and the versions of `@ethersproject/contracts` and `@ethersproject/providers` to `5.5.0` (the latest versions as of this comment)

Once that's working you'll also get another error if Metamask isn't set up properly- in `Greeter.tsx` I needed a try/catch around `setMessage` in the `useEffect`- the `await` call was throwing and causing the whole app to crash.

**Comment by iboxgithub** [comment]
Point 1 and 2 worked for me, didnt get the Metamask error, thanks @CarterAppleton

**Comment by ar4s-eth** [comment]
> Once that's working you'll also get another error if Metamask isn't set up properly- in `Greeter.tsx` I needed a try/catch around `setMessage` in the `useEffect`- the `await` call was throwing and causing the whole app to crash.

@CarterAppleton

The first part of your very helpful reply got me passed the initial compile errors, thank you!

I've wrapped the `setMessage` in the `useEffect` with:

 ```
 useEffect(() => {
    const doAsync = async () => {
      if (!greeter.instance) return;
      console.log("Greeter is deployed at ", greeter.instance.address);
      try {
        setMessage(await greeter.instance.greet());
      } catch (error) {
        console.log(error)
      }
    };
    doAsync();
  }, [greeter]);
```
(I'm a fairly new dev, and I hope I've done that correctly)

I'm seeing: 

```
Failed to compile.

./src/components/Greeter.tsx
Module not found: Can't resolve './../hardhat/SymfoniContext' in '/Users/ar4s/dev/consensys/blockchain-bootcamp-final-project/frontend/src/components'
```

Was this the error you were seeing as well? 

**Never mind lol - I'm understanding that the SymfoniContext file is missing and I have no idea why, it's a fresh install.**
